# GENERATED by Rex::Database::MySQL module

# For advice on how to change settings please see
# /etc/mysql/conf.d/my.cfg.tpl
# http://dev.mysql.com/doc/refman/5.6/en/server-configuration-defaults.html

[mysqld]
#------------------------------------------------------------------------------
# CUSTOMIZED OPTIONS
#------------------------------------------------------------------------------

# Add settings for extensions here
<% foreach my $setting (@{$settings}){ %>
<%= keys %$setting %> = <%= values %$setting %><% } %>

[mysqld_safe]
log-error=/var/log/mysql/mysqld.log
#pid-file=/var/run/mysqld/mysqld.pid